# https://github.com/openai/codex/blob/main/docs/config.md


approval_policy = "on-request"
preferred_auth_method = "chatgpt"
sandbox_mode = "workspace-write"
model = "gpt-5.2-codex"
model_reasoning_effort = "medium"
notify = ["$HOME/.local/bin/codex-notify"]

[features]
rmcp_client = true

[mcp_servers.context7]
args = ["-y", "@upstash/context7-mcp"]
command = "npx"

[mcp_servers.linear]
url = "https://mcp.linear.app/mcp"

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest"]

[sandbox_workspace_write]
network_access = true
writable_roots = [
  "$GOPATH",
  "$XDG_CACHE_HOME",
  "$XDG_CONFIG_HOME"
]

[tui]
notifications = [ "approval-requested" ]
