#:schema https://developers.openai.com/codex/config-schema.json
# https://github.com/openai/codex/blob/main/docs/config.md

approval_policy = "on-request"
check_for_update_on_startup = false
sandbox_mode = "workspace-write"
model = "gpt-5.3-codex"
model_reasoning_effort = "medium"
notify = ["$HOME/.local/bin/codex-notify"]
file_opener = "vscode"

[features]
shell_snapshot = true
unified_exec = true

[mcp_servers.context7]
args = ["-y", "@upstash/context7-mcp"]
command = "npx"

[sandbox_workspace_write]
network_access = true
writable_roots = [
  "$GOPATH",
  "$XDG_CACHE_HOME",
  "$XDG_CONFIG_HOME"
]

[tui]
notifications = [ "approval-requested" ]
