# https://github.com/openai/codex/blob/main/docs/config.md


approval_policy = "on-request"
preferred_auth_method = "chatgpt"
sandbox_mode = "workspace-write"
model = "gpt-5.1-codex-max"
model_reasoning_effort = "medium"

[features]
rmcp_client = true

[mcp_servers.context7]
args = ["-y", "@upstash/context7-mcp"]
command = "npx"

[mcp_servers.linear]
url = "https://mcp.linear.app/mcp"

[sandbox_workspace_write]
network_access = true
writable_roots = [
  "$GOPATH",
  "$XDG_CACHE_HOME",
  "$XDG_CONFIG_HOME"
]

[tui]
notifications = true
